<?php

// $Id$


function islandora_large_image_sp_required_fedora_objects() {


  $module_path = drupal_get_path('module', 'islandora_large_image_sp');

  // make database insertions here.
  $result = db_result(db_query('Select name from {xml_forms} where name = "%s"', 'Islandora MODS Form'));
  if (!$result) {
    $filename = "$module_path/xml/mods_large_image.xml";
    $form_as_string = file_get_contents($filename);
    $object = new stdClass();
    $object->name = 'Islandora MODS Form';
    $object->form = $form_as_string;
    $result = drupal_write_record('xml_forms', $object);
  }

  $result = db_result(db_query('Select name from {xml_forms} where name = "%s"', 'Upload Existing Mods'));
  if (!$result) {
    $filename = "$module_path/xml/mods_large_image.xml";
    $form_as_string = file_get_contents($filename);
    $object = new stdClass();
    $object->name = 'Upload Existing Mods';
    $object->form = $form_as_string;
    $result = drupal_write_record('xml_forms', $object);
  }

  return array(
    'islandora_large_image_sp' => array(
      'module' => 'islandora_large_image_sp',
      'title' => 'Islandora Large image Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_large_image_cmodel',
          'label' => 'Islandora large image content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/islandora_sp_large_image_cmodel.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_viewer_sdef.xml",
          'pid' => 'islandora:viewerSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_viewer_sdep_large_image.xml",
          'pid' => 'islandora:viewerSdep-large_image_sp',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2Sdef.xml",
          'pid' => 'islandora:jp2Sdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2Sdep-large_image.xml",
          'pid' => 'islandora:jp2Sdep-large_image',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_mods2html_sdef.xml",
          'pid' => 'islandora:mods2htmlSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_large_image_mods2htmlSdep.xml",
          'pid' => 'islandora:mods2htmlSdep-large_image',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),

        array(
          'pid' => 'islandora:sp_large_image_collection',
          'label' => 'Islandora Large Image Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:top',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/large_image_collection_policy.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

