<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_large_image_menu() {
  $items = array();
  $items['admin/islandora/large_image'] = array(
    'title' => 'Large Image Collection',
    'description' => 'Configure the Large Image Solution Pack.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_large_image_admin'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called
 * (the pids colon should be replaced with a dash).
 */
function islandora_large_image_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_large_image' => array(
      'template' => 'theme/islandora-large-image',
      // We can add pids to the end of this pattern in our preprocess function
      // and templates will be able to have have a pid appended to the template
      // name to overide a template on a per object basis. An example template
      // would be named islandora-basic-image--islandora-27.tpl.phps.
      'pattern' => 'islandora_large_image__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_large_image_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_large_image');
  // Large Image Content Model.
  $large_image_content_model = $connection->repository->constructObject('islandora:sp_large_image_cmodel');
  $large_image_content_model->owner = 'fedoraAdmin';
  $large_image_content_model->label = 'Islandora Large Image Content Model';
  $large_image_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM Datastream.
  $datastream = $large_image_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_sp_large_image_cmodel.xml", FALSE);
  $large_image_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $large_image_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_large_image_ds_composite_model.xml", FALSE);
  $large_image_content_model->ingestDatastream($datastream);
  // Large Image Collection.
  $large_image_collection = $connection->repository->constructObject('islandora:sp_large_image_collection');
  $large_image_collection->owner = 'fedoraAdmin';
  $large_image_collection->label = 'Large Image Collection';
  $large_image_collection->models = 'islandora:collectionCModel';
  $large_image_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $large_image_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_large_image_collection_policy.xml", FALSE);
  $large_image_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $large_image_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $large_image_collection->ingestDatastream($datastream);
  return array(
    'islandora_large_image' => array(
      'title' => 'Islandora large image',
      'objects' => array(
        $large_image_content_model,
        $large_image_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_large_image_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_large_image');
  return array(
    'Large image MODS form' => array(
      'form_file' => "$module_path/xml/islandora_large_image_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_large_image_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_large_image_mods_form' => array(
      'content_model' => 'islandora:sp_large_image_cmodel',
      'form_name' => 'Large image MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_large_image_islandora_sp_large_image_cmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_large_image', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_large_image_islandora_sp_large_image_cmodel_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_large_image', 'includes/derivatives');
  islandora_large_image_create_all_derivatives($object, FALSE);
}

/**
 * Implements hook_preprocess().
 */
function islandora_large_image_preprocess_islandora_large_image(&$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  // Get DC metadata.
  try {
    $dc = $islandora_object['DC']->content;
    $dc_object = DublinCore::importFromXMLString($dc);
  }
  catch (Exception $e) {
    drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->asArray() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_large_image__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  // Thumbnail.
  if (isset($islandora_object['TN'])) {
    $params = array(
      'title' => $islandora_object->label,
      'path' => url("islandora/object/{$islandora_object->id}/datastream/TN/view"),
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);
  }
  module_load_include('inc', 'islandora', 'includes/solution_packs');

  // Get token to allow access to XACML protected datastreams.
  // Always use token authentication in case there is a global policy.
  module_load_include('inc', 'islandora', 'includes/authtokens');
  $token = islandora_get_object_token($islandora_object->id, 'JP2', 2);
  $jp2_url = url("islandora/object/{$islandora_object->id}/datastream/JP2/view",
    array(
      'absolute' => TRUE,
      'query' => array('token' => $token),
    ));
  // Display large image.
  $params = array(
    'jp2_url' => $jp2_url,
  );
  $viewer = islandora_get_viewer($params, 'islandora_large_image_viewers', $islandora_object);
  $variables['islandora_content'] = '';
  if ($viewer) {
    if (strpos($viewer, 'islandora-openseadragon') !== FALSE) {
      if ($islandora_object['JP2']) {
        $variables['image_clip'] = l(t('Clip Image'), "islandora/object/{$islandora_object->id}/print", array('attributes' => array('title' => 'Clip Image', 'id' => 'clip')));
      }
    }
    $variables['islandora_content'] = $viewer;
  }
  // If no viewer is configured just show the jpeg.
  elseif (isset($islandora_object['JPG'])) {
    $params = array(
      'title' => $islandora_object->label,
      'path' => url("islandora/object/{$islandora_object->id}/datastream/JPG/view"),
    );
    $variables['islandora_content'] = theme('image', $params);
  }
  else {
    $variables['islandora_content'] = NULL;
  }
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_large_image_islandora_sp_large_image_cmodel_islandora_ingest_steps() {
  return array(
    'islandora_large_image_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_large_image_image_upload_form',
      'module' => 'islandora_large_image',
      'file' => 'includes/image_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_process_theme().
 */
function islandora_large_image_preprocess_islandora_object_print(array &$variables) {
  $object = $variables['object'];
  if (in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $url = url("islandora/object/{$object->id}", array('absolute' => TRUE));
    $variables['content']['link'] = array(
      '#weight' => -10,
      '#markup' => t('Persistent link: ') . l($url, $url),
    );
  }
}

/**
 * Implements hook_process_theme().
 */
function islandora_large_image_process_islandora_object_print(array &$variables) {
  $object = $variables['object'];
  if (in_array('islandora:sp_large_image_cmodel', $object->models)) {
    $clip = isset($variables['clip']) ? $variables['clip'] : NULL;
    $variables['content']['buttons'] = array(
      '#access' => isset($clip),
      '#prefix' => '<div>',
      '#suffix' => '</div></br>',
      '#weight' => -5,
      'print' => array(
        '#prefix' => '<strong>',
        '#markup' => l(t('Print'), 'javascript:window.print();', array('external' => TRUE)),
        '#suffix' => '</strong>',
        '#weight' => -5,
      ),
      '0' => array(
        '#markup' => ' | ',
        '#weight' => -5,
      ),
      'download_clip' => array(
        '#prefix' => '<strong>',
        '#markup' => l(t('Download Image'), "islandora/object/{$object->id}/download_clip", array(
                     'query' => array('clip' => $clip))),
        '#suffix' => '</strong>',
        '#weight' => -5,
      ),
    );
  }
}
