<?php


/**
 * islandora large image sp required fedora objects
 * @return type 
 */
function islandora_large_image_sp_required_fedora_objects() {

  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  $module_path = drupal_get_path('module', 'islandora_large_image_sp');
  $form_name = 'Islandora Large Image MODS Form';
  $form_xml = file_get_contents("$module_path/xml/mods_large_image.xml");
  solution_pack_add_form($form_name, $form_xml);
  solution_pack_add_form_association('islandora:sp_large_image_cmodel', $form_name);


  return array(
    'islandora_large_image_sp' => array(
      'module' => 'islandora_large_image_sp',
      'title' => 'Islandora Large image Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_large_image_cmodel',
          'label' => 'Islandora large image content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/islandora_sp_large_image_cmodel.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_viewer_sdef.xml",
          'pid' => 'islandora:viewerSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_viewer_sdep_large_image.xml",
          'pid' => 'islandora:viewerSdep-large_image_sp',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2sdef.xml",
          'pid' => 'islandora:jp2Sdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2Sdep-large_image.xml",
          'pid' => 'islandora:jp2Sdep-large_image',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_mods2html_sdef.xml",
          'pid' => 'islandora:mods2htmlSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'foxml_file' => "$module_path/xml/islandora_large_image_mods2htmlSdep.xml",
          'pid' => 'islandora:mods2htmlSdep-large_image',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        array(
          'pid' => 'islandora:sp_large_image_collection',
          'label' => 'Islandora Large Image Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/large_image_collection_policy.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

